# ----------------------------
# Whitelist: words that should NOT be autocorrected
# Mapping is lowercase → proper capitalization
# ----------------------------
WHITELIST = {
    # Programming Languages
    "python": "Python",
    "java": "Java",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "c": "C",
    "c++": "C++",
    "c#": "C#",
    "go": "Go",
    "rust": "Rust",
    "ruby": "Ruby",
    "php": "PHP",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "scala": "Scala",
    "perl": "Perl",
    "matlab": "MATLAB",
    "r": "R",

    # Frameworks / Libraries
    "django": "Django",
    "flask": "Flask",
    "fastapi": "FastAPI",
    "spring": "Spring",
    "hibernate": "Hibernate",
    "react": "React",
    "angular": "Angular",
    "vue": "Vue",
    "svelte": "Svelte",
    "nextjs": "Next.js",
    "nuxtjs": "Nuxt.js",
    "express": "Express",
    "laravel": "Laravel",
    "symfony": "Symfony",
    "rails": "Rails",
    "dotnet": ".NET",
    "nodejs": "Node.js",

    # AI / ML / Data Science
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "keras": "Keras",
    "scikit": "scikit-learn",
    "sklearn": "scikit-learn",
    "numpy": "NumPy",
    "pandas": "Pandas",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "nltk": "NLTK",
    "spacy": "spaCy",
    "huggingface": "HuggingFace",
    "openai": "OpenAI",
    "gpt": "GPT",
    "bert": "BERT",
    "llama": "LLaMA",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",

    # Cloud / DevOps
    "aws": "AWS",
    "azure": "Azure",
    "gcp": "GCP",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "jenkins": "Jenkins",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "circleci": "CircleCI",
    "travisci": "TravisCI",
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",

    # Databases
    "mysql": "MySQL",
    "postgresql": "PostgreSQL",
    "sqlite": "SQLite",
    "mongodb": "MongoDB",
    "cassandra": "Cassandra",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "dynamodb": "DynamoDB",

    # Tools / Platforms
    "jira": "Jira",
    "slack": "Slack",
    "notion": "Notion",
    "figma": "Figma",
    "trello": "Trello",
    "asana": "Asana",
    "zoom": "Zoom",
    "skype": "Skype",
    "teams": "Teams",
    "whatsapp": "WhatsApp",
    "linkedin": "LinkedIn",
    "twitter": "Twitter",
    "facebook": "Facebook",
    "instagram": "Instagram",

    # People / Custom Names
    "vishwajeet": "Vishwajeet",
    "lingobot": "LingoBot",
    "google": "Google",
    "microsoft": "Microsoft",
    "apple": "Apple",
    "amazon": "Amazon",
    "meta": "Meta",
    "tesla": "Tesla",
    "spacex": "SpaceX",
    "nvidia": "NVIDIA",
    "intel": "Intel",
    "ibm": "IBM",

    # Months
    "january": "January",
    "february": "February",
    "march": "March",
    "april": "April",
    "may": "May",
    "june": "June",
    "july": "July",
    "august": "August",
    "september": "September",
    "october": "October",
    "november": "November",
    "december": "December",

    # Weekdays
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "sunday": "Sunday",

    # Countries
    "india": "India",
    "usa": "USA",
    "uk": "UK",
    "germany": "Germany",
    "france": "France",
    "italy": "Italy",
    "spain": "Spain",
    "japan": "Japan",
    "china": "China",
    "canada": "Canada",
    "australia": "Australia",
    "brazil": "Brazil",
    "russia": "Russia",
    "mexico": "Mexico",
    "south africa": "South Africa",

    # Cities
    "new york": "New York",
    "los angeles": "Los Angeles",
    "san francisco": "San Francisco",
    "london": "London",
    "paris": "Paris",
    "berlin": "Berlin",
    "rome": "Rome",
    "madrid": "Madrid",
    "tokyo": "Tokyo",
    "beijing": "Beijing",
    "shanghai": "Shanghai",
    "bangalore": "Bangalore",
    "mumbai": "Mumbai",
    "delhi": "Delhi",
    "singapore": "Singapore",
    "sydney": "Sydney",
    "toronto": "Toronto",
    "dubai": "Dubai"
}

# ----------------------------
# Stopwords: words that should NOT be capitalized
# ----------------------------
STOPWORDS = {
    "a", "an", "the", "and", "or", "but", "nor",
    "for", "yet", "so", "to", "in", "on", "at", "by",
    "of", "up", "down", "over", "under", "with", "from",
    "as", "is", "am", "are", "was", "were", "be", "been",
    "has", "have", "had", "do", "does", "did",
    "not", "no", "yes", "if", "then", "else", "when",
    "because", "since", "until", "while", "about", "after",
    "before", "during", "through", "between", "into", "out",
    "again", "further", "once"
}
